version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./neurohub.db
    command: uv run uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend
    command: uv run streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0